// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuWFKsJKfydnhXTjEbdsCXn11lszpNRk0',
    appId: '1:525216688485:web:a88e1a80fb6a154b00198c',
    messagingSenderId: '525216688485',
    projectId: 'board-money-24cda',
    authDomain: 'board-money-24cda.firebaseapp.com',
    databaseURL: 'https://board-money-24cda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'board-money-24cda.appspot.com',
    measurementId: 'G-QYDYNNZWJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkzQ4ht4R2XMz6g8mAgfoB7Ls6OD5LntY',
    appId: '1:525216688485:android:e771c244b02faae200198c',
    messagingSenderId: '525216688485',
    projectId: 'board-money-24cda',
    databaseURL: 'https://board-money-24cda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'board-money-24cda.appspot.com',
  );
}
